language: csharp
solution: PriorityQueue.sln
install:
  - nuget restore PriorityQueue.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PriorityQueue.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./PriorityQueue.Tests/bin/Release/PriorityQueue.Tests.dll
