language: csharp
solution: PriorityQueue.sln
install:
  - nuget restore PriorityQueue.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PriorityQueue.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./PriorityQueue.Tests/bin/Release/PriorityQueue.Tests.dll
